apiVersion: v1
kind: ConfigMap
metadata:
    name: aws-auth
    namespace: kube-system
data:
    mapRoles: |
        - rolearn: arn:aws:iam::293914840456:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
            - system:masters
